theme: jekyll-theme-slate
title: Dan Brennan
description: Rounded IT Consultant with a demonstrated history of working in the information technology and services industry. Strong professional with an Associateâ€™s Degree focused in Computer Programming and Analysis.
